---
- name: 'Install dependencies'
  tags: 'mongodb'
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - 'python-pycurl' # Required by Ansible for adding apt repositories

- name: 'Add MongoDB apt key'
  tags: 'mongodb'
  sudo: 'yes'
  apt_key: >
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: 'Add MongoDB apt repository'
  tags: 'mongodb'
  sudo: 'yes'
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    state=present

- name: 'Install MongoDB'
  tags: 'mongodb'
  sudo: 'yes'
  apt: >
    pkg=mongodb-10gen
    state=present
    update_cache=true